export const WISHLIST_CREATE_REQUEST = "WISHLIST_CREATE_REQUEST"
export const WISHLIST_CREATE_SUCCESS = "WISHLIST_CREATE_SUCCESS"
export const WISHLIST_CREATE_FAIL = "WISHLIST_CREATE_FAIL"
export const WISHLIST_CREATE_RESET = "WISHLIST_CREATE_RESET"

export const WISHLIST_LIST_MY_REQUEST = "WISHLIST_LIST_MY_REQUEST";
export const WISHLIST_LIST_MY_SUCCESS = "WISHLIST_LIST_MY_SUCCESS";
export const WISHLIST_LIST_MY_FAIL = "WISHLIST_LIST_MY_FAIL";
export const WISHLIST_LIST_MY_RESET = "WISHLIST_LIST_MY_RESET";

export const WISHLIST_DELETE_REQUEST = "WISHLIST_DELETE_REQUEST";
export const WISHLIST_DELETE_SUCCESS = "WISHLIST_DELETE_SUCCESS";
export const WISHLIST_DELETE_FAIL = "WISHLIST_DELETE_FAIL";